#!/bin/bash

# Add an account for Dave with his key.
# Should be usable for Debian boxes, at least.
# This is intended to let people easily create me an account with my SSH key,
# just by wget'ing it and piping it to bash.

# I'm dave on work boxes, davidp elsewhere
if [[ "`hostname -f`" == *uk2* ]]; then
    NEWUSER=dave
else
    NEWUSER=davidp
fi


KEYURL=http://www.preshweb.co.uk/downloads/keys/david-precious-ssh-key

echo "Creating user account $NEWUSER"
useradd --create-home --comment "David Precious <davidp@preshweb.co.uk>" $NEWUSER

echo "Adding SSH key for $NEWUSER from $KEYURL"
mkdir /home/$NEWUSER/.ssh
wget -O /home/$NEWUSER/.ssh/authorized_keys $KEYURL

# Make sure permissions are correct so the key is accepted:
chown -R $NEWUSER /home/$NEWUSER/.ssh
chmod 700 /home/$NEWUSER
chmod 700 /home/$NEWUSER/.ssh
chmod 600 /home/$NEWUSER/.ssh/authorized_keys

# Add me to sudo/wheel group (depending on distro, one or the other of this
# should work, one will probably fail)
echo "Adding $NEWUSER to sudo/wheel group"
usermod -a -G sudo  $NEWUSER
usermod -a -G wheel $NEWUSER

# Make sure I've got an appropriate shell.  Some Ubuntu boxes seem to default me
# to /bin/sh, which isn't helpful.
echo "Setting shell to /bin/bash"
chsh -s /bin/bash $NEWUSER

echo "All done."

