#!/usr/bin/perl

# Read through Chimera log files, and print any requests matching the supplied
# regex, in their entirety.
#
# Quick and dirty bodge until we have proper centralised log searching
# facilities.

use strict;
my $regex = shift;
my $request;
while (my $line = <>) {
    # if this is the start of a new request, see if the previous request matches
    # our pattern, and print it if so
    if ($line =~ /^\d{8}/) {
        if ($request =~ /$regex/) {
            print $request;
            print "*" x 60 . "\n";
        }
        $request = $line;
    } else {
        $request .= $line;
    }
}


	
