#!/bin/bash

# Set up links to my profile, vimrc etc.

# If the destination exists, but is not a symlink, then rename it and create
# our desired symlink in place
function symlink {
    source=$1
    dest=$2
    
    if [[ -e $dest && ! -L $dest ]]; then
        echo "Renaming existing $dest to $dest.old"
        mv $dest $dest.old;
    fi

    if [[ ! -L $dest ]]; then
        echo "Symlinking $dest to $source";
        ln -sf $source $dest;
    fi
}



symlink ~/dotfiles/profile  ~/.profile
symlink ~/dotfiles/vim      ~/.vim
symlink ~/dotfiles/vimrc    ~/.vimrc
symlink ~/dotfiles/screenrc ~/.screenrc
symlink ~/dotfiles/zim/style.conf ~/.config/zim/style.conf

if [ -x /usr/bin/terminator ]; then
    mkdir -p ~/.config/terminator 2>/dev/null
    symlink ~/dotfiles/terminator/config ~/.config/terminator/config
fi

# Make sure GNU parallel won't show the citation stuff
mkdir -p ~/.parallel
touch ~/.parallel/will-cite

symlink ~/dotfiles/re.pl ~/.re.pl

# Finally, source the new profile
. ~/.profile

