#!/bin/bash

# Set up links to my profile, vimrc etc, ensure the repo checkout is correct,
# add auto-update cronjob if not already present, etc.
#
# Intended to be idempotent so it's safe to run this script from a cronjob
# to auto-update.
#
# This means that setting up my preferred environment on a new box can be as
# simple as checking out the dotfiles repo and running this script from
# that checkout.

# If the destination exists, but is not a symlink, then rename it and create
# our desired symlink in place
function symlink {
    source=$1
    dest=$2
    
    if [[ -e $dest && ! -L $dest ]]; then
        echo "Renaming existing $dest to $dest.old"
        mv $dest $dest.old;
    fi

    if [[ ! -L $dest ]]; then
        echo "Symlinking $dest to $source";
        ln -sf $source $dest;
    fi
}



symlink ~/dotfiles/profile  ~/.bashrc
symlink ~/dotfiles/vim      ~/.vim
symlink ~/dotfiles/vimrc    ~/.vimrc
symlink ~/dotfiles/screenrc ~/.screenrc

if [ -d ~/.config/zim ]; then
    symlink ~/dotfiles/zim/style.conf ~/.config/zim/style.conf
fi

if [ -x /usr/bin/terminator ]; then
    mkdir -p ~/.config/terminator 2>/dev/null
    symlink ~/dotfiles/terminator/config ~/.config/terminator/config
fi

# Make sure GNU parallel won't show the citation stuff
mkdir -p ~/.parallel
touch ~/.parallel/will-cite

symlink ~/dotfiles/re.pl ~/.re.pl


# See if I already have a cronjob configured to update my dotfiles
# automatically; if not, add it...
if crontab -l 2>/dev/null | grep dotfiles > /dev/null; then
    echo "Auto-update cronjob already exists"
else
    echo "Adding auto-update cronjob"
    crontab -l > crontab-tmp 2>/dev/null
    cat cron-entry >> crontab-tmp
    crontab crontab-tmp
    rm crontab-tmp
fi

# Make sure the dotfiles repo checkout has the https:// publicly-accessible
# URL for fetching from the origin, but the git@ one (SSH with key) for pushing
# - if we have git@ for fetch, then the cronjob to auto-update can't work.
git remote set-url origin https://github.com/bigpresh/dotfiles.git
git remote set-url --push origin git@github-personal:bigpresh/dotfiles.git
git pull

# Finally, source the new profile
. ~/.bashrc

